### ISSUE TITLE
Location tracking in water sports

### ISSUE THREAD

**Issue by rodrigovaras** [maddevsio/mad-location-manager#83]
Was wondering if the library is capable to handle with reasonable accuracy a run in a sport where the speed and location is crucial.
Basically one pass takses around 16.1 secs and the position of the skier describe 6 turns.  The idea is later to track with good precision the skier path and show speed location to later be analyzed by coaches.
I explore the fastest GPS and they have max rate of 5HZ which i think is not enough to later analyze the data.

Concrete question:
- Can i reduce the GPS min sample settings from 2 secs to something like 0.5 ?
- Will the accelerometer samples fusioned with GPS a good way to resolve what i just describe?

**Comment by Lezh1k** [comment]
You need not only accelerometer here. You need to look for good accelerometer, gyroscope and magnetometer + good GPS receiver. 
I guess best way is to place those sensors system on leg (below knee and above foot I think), because you'll be able to reset accumulated accelerometer error.  

And you can fuse these sensors with GPS using Kalman filter. 
I think you can use parts of code from this repo (branch lib). There is C implementation of Kalman filter and Madgwick filter. 
But I don't think you need to use this library as main solution for your task. You need implement own solution, based on this library. 

About 2Hz for GPS receivers - I think you need to take a look at (https://www.sparkfun.com/products/retired/9758). They say: "The SUP500F features various update rates up to 10Hz" .  Maybe you can use it without any sensor fusion :)

Best regards,
Oleg
